### ISSUE TITLE
How to run on CLI only (no Colab)?

### ISSUE THREAD

**Issue by fakerybakery** [asigalov61/Pentagram-Music-Transformer#1]
Hi,
Is there a way to generate music using CLI only (without Colab) on CPU (no CUDA)?
Thanks in advance!

**Comment by asigalov61** [comment]
@fakerybakery Yes, of'course.

But you will need to change the code a bit and it will be quite slow.

See this post as an example:
https://github.com/asigalov61/Los-Angeles-Music-Composer/discussions/7#discussioncomment-7010266

And if you still need help, let me know :)

ALex

**Comment by fakerybakery** [comment]
Thanks!

**Comment by asigalov61** [comment]
@fakerybakery You are welcome!

Btw, thank you for interest in my projects and for staring my repos :)

I don't know if you got my email but I could use help with web/frontend for my projects so if you interested/can do it/have time, let me know.

ALex
